# Generated by Django 2.1.7 on 2019-03-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('add_data', models.DateField()),
                ('author', models.CharField(max_length=20)),
                ('public', models.CharField(max_length=20)),
                ('get_times', models.IntegerField()),
                ('is_borrow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('sex', models.BooleanField(default=False)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
