# Generated by Django 2.1.7 on 2019-03-09 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrow_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borDate', models.DateField()),
                ('deadline', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_book.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_book.user')),
            ],
        ),
    ]
